#!/bin/bash
# This script will install all other scripts...

OVPNPATH=$1

function get_ovpn_user(){
    OVPNUSER=$(cat $OVPNPATH/server.conf | grep user | awk {'print $2'})
    if [[ $? > 0 ]];then 
        echo "Error searching fur OpenVPN User..."
        exit 1;
    fi
}

function install_connection_scripts(){
    chmod +x connect disconnect
    cp connect disconnect $OVPNPATH/scripts
    cat $OVPNPATH/server.conf | grep "script-security" > /dev/null 2>&1
    if [[ $? == 1 ]];then
        echo "script-security 2" >> $OVPNPATH/server.conf;
    fi
    cat $OVPNPATH/server.conf | grep "client-connect" > /dev/null 2>&1
    if [[ $? == 0 ]];then
        sed -i.bak "s/client-connect.*/client-connect $OVPNPATH/scripts/connect/g" $OVPNPATH/server.conf
    else
        echo "client-connect "$OVPNPATH/scripts/connect"" >> $OVPNPATH/server.conf
    fi
    cat $OVPNPATH/server.conf | grep "client-disconnect" > /dev/null 2>&1
    if [[ $? == 0 ]];then
        sed -i.bak "s/client-connect.*/client-disconnect $OVPNPATH/scripts/disconnect/g" $OVPNPATH/server.conf
    else
        echo "client-disconnect "$OVPNPATH/scripts/disconnect"" >> $OVPNPATH/server.conf
    fi
}

if [[ $UID > 0 ]];then
    echo "Please run as root..."
    exit 1;
fi

if [[ -z $1 ]];then
    echo "Usage: $0 path/to/openvpn";
    exit 1
fi
test -e $OVPNPATH/server.conf
if [[ $? == 1 ]];then
    echo "$OVPNPATH/server.conf not found!"
    exit 1
else
    get_ovpn_user
    test -d $OVPNPATH/scripts
    if [[ $? == 1 ]];then
        mkdir -p $OVPNPATH/scripts
        install_connection_scripts
        chown -R $OVPNUSER $OVPNPATH/scripts
    fi
    test -d /var/log/openvpn
    if [[ $? == 0 ]];then
        mkdir -p /var/log/openvpn
        chown -R $OVPNUSER /var/log/openvpn;
    fi
fi
echo "Please restart your OpenVPN-Server"